stages:
  - build
  - deploy

include:
  - local: 'lib/BuildDeployWeb.gitlab-ci.yml'

# ----------------------------------------------------------------------------------------
# Staging

deploy_staging:
  extends: .deploy
  only:
    - staging
  environment:
    name: staging
    url: https://test.binaryone.ch/grallinger/web/
  script:
    - npm run-script deploy:craft -- $(echo "$DEPLOYFTPSTAGING" | base64 -d) || echo "deployment skipped, not available"
    - npm run-script deploy:webroot -- $(echo "$DEPLOYFTPSTAGING" | base64 -d) || echo "deployment skipped, not available"

# ----------------------------------------------------------------------------------------
# Production

deploy_production:
  extends: .deploy
  only:
    - master
  when: manual
  environment:
    name: production
  script:
    - npm run-script deploy:craft -- $(echo "$DEPLOYFTPPRODUCTION" | base64 -d) || echo "deployment skipped, not available"
    - npm run-script deploy:webroot -- $(echo "$DEPLOYFTPPRODUCTION" | base64 -d) || echo "deployment skipped, not available"
