field: f149b028-a15f-4397-b423-455f65a2f80d # Webkit Footer Socialmedia
fieldLayouts:
  db9e4743-e446-48b3-91f2-3efd32cf89fd:
    tabs:
      -
        elements:
          -
            fieldUid: c260b779-262e-432f-bcdf-a7f932388d26 # Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c260b779-262e-432f-bcdf-a7f932388d26: # Url
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialMediaUrl
    instructions: ''
    name: Url
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: instagram
name: Instagram
sortOrder: 3
