field: c282063a-f8a4-4b79-b8bd-7e9fd0da9205 # Double Blocks
fieldLayouts:
  b9f50392-ec5b-46a8-b1fc-0ce5cb73138b:
    tabs:
      -
        elements:
          -
            fieldUid: a51c3392-7a95-4231-85f0-c10f4c3cff6a # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f9f5435-4665-4d01-b96a-2fc61988a7fd # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84d94f7d-8ccf-48b1-9edc-939602e04244 # Link Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9f9f5435-4665-4d01-b96a-2fc61988a7fd: # Text
    contentColumnType: string(768)
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: 192
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  84d94f7d-8ccf-48b1-9edc-939602e04244: # Link Button
    contentColumnType: text
    fieldGroup: null
    handle: linkButton
    instructions: 'Wenn der eigene Linktext leer ist, wird standardmässig der runde Button verwendet.'
    name: 'Link Button'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames:
        3: entry
        6: custom
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: language
    type: typedlinkfield\fields\LinkField
  a51c3392-7a95-4231-85f0-c10f4c3cff6a: # Titel
    contentColumnType: string(120)
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 4
