baseUrl: $EN_SITE_URL
enabled: true
handle: craftWebkitEn
hasUrls: true
language: en
name: 'craft webkit EN'
primary: false
siteGroup: 0b254874-1508-427b-8a4b-0fdf47a6fb56 # craft webkit
sortOrder: 2
