childBlocks: ''
field: 910ed34d-c1a1-40ba-8576-af9f30717649 # Webkit Module
fieldLayouts:
  dbff649e-fa47-4067-a74f-fa1deb64c566:
    tabs:
      -
        elements:
          -
            fieldUid: 7e64eee6-5cf0-40d2-bec2-5b5cf0a024e0 # Heading
            instructions: ''
            label: Titel
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b31068bd-6e4d-465e-9648-6442bf67c853 # Gallery
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c35398c-fa5f-4c8a-a8f7-40f2a4f60eea # Mehr Laden Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c25a7824-8c38-4d6b-bc9d-b568f7503fd1 # Weniger anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Galerie
        sortOrder: 1
handle: gallery
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Bild Galerie'
sortOrder: 10
topLevel: true
