childBlocks: ''
field: 2a2eb0bd-8dc4-4700-84d9-aae01b0f498c # Webkit Footer Module
fieldLayouts:
  5f5e39d7-e5a8-4955-a25c-b683dd215815:
    tabs:
      -
        elements:
          -
            fieldUid: 7e64eee6-5cf0-40d2-bec2-5b5cf0a024e0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 039cc497-f979-4f93-aef8-28a8e5458b59 # Webkit Navigation
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: nav
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Nav
sortOrder: 2
topLevel: true
