childBlocks: ''
field: 86c4e5d6-fede-4687-b2d2-6395be33c1a9 # Navigation Mehrstufig
handle: navigationStufe1OhneLink
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Navigation Stufe 1 ohne Link'
sortOrder: 3
topLevel: true
