childBlocks: ''
field: 86c4e5d6-fede-4687-b2d2-6395be33c1a9 # Navigation Mehrstufig
fieldLayouts:
  a643a50f-87d8-4b0f-b568-5b4fcce7ff93:
    tabs:
      -
        elements:
          -
            fieldUid: e12c3611-0537-4be1-8b17-1e6b0970fd25 # Link Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Link
        sortOrder: 1
handle: navigationStufe1
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Navigation Stufe 1'
sortOrder: 1
topLevel: true
