childBlocks: ''
field: 910ed34d-c1a1-40ba-8576-af9f30717649 # Webkit Module
fieldLayouts:
  811eed4b-205d-4b18-8da3-bfc75295cab9:
    tabs:
      -
        elements:
          -
            fieldUid: 56580202-cceb-4d6c-9281-9506a629e304 # Text Grid Block
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c35398c-fa5f-4c8a-a8f7-40f2a4f60eea # Mehr Laden Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Grid
        sortOrder: 1
handle: textgrid
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: '3-5er Raster Text'
sortOrder: 15
topLevel: true
