contentColumnType: string
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: akkordeon
instructions: ''
name: Akkordeon
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 01dbe3db-905b-4335-b3ee-d5e3dc9bd99f # Text
        -
          __assoc__:
            -
              - width
              - ''
      -
        - eb9f8e15-d4ad-4131-bdde-d5d44ddd7e08 # Titel
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_akkordeon}}'
  fieldLayout: matrix
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: 'Akkordeon hinzufügen'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
