contentColumnType: string
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: doubleGrid
instructions: ''
name: Zweiergrid
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 1114df9c-e4a5-460c-97a0-f194756acbf0 # Link Button
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 6750e875-70a1-47f8-88e9-63e7789ff6c2 # Bild
        -
          __assoc__:
            -
              - width
              - ''
      -
        - be4a5021-5ad6-4cc9-8298-03944edceaeb # Heading
        -
          __assoc__:
            -
              - width
              - ''
      -
        - d7ec1402-38b7-4bb0-815d-82d5fb690f50 # Text
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e9992a02-2a0c-4b1a-b397-180a26c73cac # Titel
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_doublegrid}}'
  fieldLayout: matrix
  maxRows: '2'
  minRows: '2'
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
