contentColumnType: text
fieldGroup: 51f9c559-f4db-4a9c-97d9-065574859d27 # Formular
handle: formSubject
instructions: ''
name: Betreff
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
