contentColumnType: string(64)
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: loadMoreButton
instructions: 'Optional. Falls dieses Feld leer ist, wird ein kleiner Button mit "+" verwendet.'
name: 'Mehr Laden Button'
searchable: false
settings:
  byteLimit: null
  charLimit: 16
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
