contentColumnType: string
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: textGridBlock
instructions: ''
name: 'Text Grid Block'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 064533e8-c67c-4212-aeac-a868c8ff071a # Titel
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c4f17cab-5d3e-4f8b-a5ea-b2ee136abeec # Text
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_textgridblock}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
