contentColumnType: string(1020)
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: textLong
instructions: ''
name: 'Text Lang'
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
