contentColumnType: string(768)
fieldGroup: 1bc42527-20f2-450a-9156-9dd0f0c2cef0 # Webkit Module Fields
handle: textMedium
instructions: ''
name: 'Text Medium'
searchable: false
settings:
  byteLimit: null
  charLimit: 192
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
