contentColumnType: string
fieldGroup: e6072f5b-24cd-4730-92fd-25fe65062e61 # Common
handle: webkitModule
instructions: ''
name: 'Webkit Module'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
