field: 07a51f33-7e99-4cf8-8945-9c51e38fba91 # Slides
fieldLayouts:
  ec5e8a55-78c2-4c0d-8836-511bc7f9076c:
    tabs:
      -
        elements:
          -
            fieldUid: 72da1f4a-2839-4c2e-85ea-e4f4def3e686 # Bild
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e4aac7fc-a36c-4e43-a20f-60f372772fa3 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b1882f6-18d9-4a2f-a0f6-ebe9d3785b96 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cedc4a23-b718-415a-b098-da392c541a82 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4b1882f6-18d9-4a2f-a0f6-ebe9d3785b96: # Text
    contentColumnType: string(768)
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: 192
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  72da1f4a-2839-4c2e-85ea-e4f4def3e686: # Bild
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:9f4851cc-ccca-4537-bcd7-386d4debaca9' # Bilder
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Bild hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9f4851cc-ccca-4537-bcd7-386d4debaca9' # Bilder
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  cedc4a23-b718-415a-b098-da392c541a82: # Link
    contentColumnType: text
    fieldGroup: null
    handle: slideLink
    instructions: 'Wenn der eigene Linktext leer ist, wird standardmässig der runde Button verwendet.'
    name: Link
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames:
        3: entry
        6: custom
        9: url
      autoNoReferrer: ''
      defaultLinkName: user
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: language
    type: typedlinkfield\fields\LinkField
  e4aac7fc-a36c-4e43-a20f-60f372772fa3: # Titel
    contentColumnType: string(128)
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: 32
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
