fieldLayouts:
  553e6d08-2ea5-421f-8ef0-b3d619d0e4f9:
    tabs:
      -
        elements:
          -
            fieldUid: 86c4e5d6-fede-4687-b2d2-6395be33c1a9 # Navigation Mehrstufig
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Header footer'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 45ab70e4-8461-4197-a7e6-c64011de028e # Link Button 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f149b028-a15f-4397-b423-455f65a2f80d # Webkit Footer Socialmedia
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: navigation
name: Navigation
sortOrder: 5
